---
name: variable practice

on:
  workflow_dispatch:
    

env:
  WORKFLOW_VAR: this is workflow level variable

jobs:
  learning_variables:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: print_variables
        run: |
              echo "ORG = ${{ vars.ORG_VAR }}"
              echo "REPO = ${{vars.REPO_VAR}}"
              echo "ENV = ${{vars.ENV_VAR}}"
              echo "WORKFLOW = $WORKFLOW_VAR"

      - name: print contexts
        run: |
             echo "${{ toJSON(github) }}"
             echo "${{ toJSON(env) }}"
             echo "${{ toJSON(vars) }}"
             echo "${{ toJSON(job) }}"
             echo "${{ toJSON(steps) }}"
             echo "${{ toJSON(runner) }}"
             echo "${{ toJSON(secrets) }}"
             echo "${{ toJSON(strategy) }}"
             echo "${{ toJSON(matrix) }}"
             echo "${{ toJSON(needs) }}"
             echo "${{ toJSON(inputs) }}"
             

